### ISSUE TITLE
Verify that a worker exists when inserting the job

### ISSUE THREAD

**Issue by axelson** [sorentwo/oban#18]
Could `Oban.Job.new/2` verify that the `worker` module does exist and implements the `Oban.Worker` behavior?

While initially developing with oban I decided to rename my worker, but I forgot to rename the name of the worker at the place in the code that I enqueued the job. This resulted in a job being inserted into the `oban_jobs` table that has state `executing` but is not actually being executed.

Although perhaps the docs should more heavily recommend using `MyApp.Worker.new/2` to generate the worker changeset instead of `Oban.Job.new/2` since that way you will get an error if `MyApp.Worker.new/2` does not exist.

Also is there a way to recover from a job whose state is `executing`, but in reality is not executing?

**Comment by sorentwo** [comment]
> Could `Oban.Job.new/2` verify that the `worker` module does exist and implements the `Oban.Worker` behavior?

I'm hesitant to do this because it is entirely feasible that one app enqueues a job that will be handled by another app. For example, based on a discussion on the forum, one app may enqueue an ffmpeg based job for another app to handle. The worker is only defined in the second job processing app and they may not share any code.

> Although perhaps the docs should more heavily recommend using `MyApp.Worker.new/2` to generate the worker changeset instead of `Oban.Job.new/2` since that way you will get an error if `MyApp.Worker.new/2` does not exist.

Agreed 👍 . The docs should definitely push people to use `Worker.new` and not promote `Oban.Job.new`.

> Also is there a way to recover from a job whose state is `executing`, but in reality is not executing?

That should be done automatically when the system restarts (though I'm looking at making it something that happens periodically). The rescue is done by each queue's producer, so jobs will only be rescued for queues that are _currently_ processing jobs. Did you change the worker name and the queue name?

**Comment by sorentwo** [comment]
@axelson I've pushed up a change to emphasize `Worker.new/2` over `Job.new/2` here 
4c8b242.

I'm leaving this open for now while we try to figure out why that job is stuck as `executing`.

**Comment by axelson** [comment]
Doc changes look great!

I'm not sure why they got stuck as executing, initially it was because I enqueued the worker with a name that was incorrect because I had changed the name. Then I renamed the worker name in the `oban_jobs` table and restarted my server but it was still not working. But after doing that again now it was picked up and ran. Potentially there was an issue because I had two iex sessions running?

**Comment by sorentwo** [comment]
> Potentially there was an issue because I had two iex sessions running?

That could be the issue. If the original iex session was still open then the postgres session that locked the job was probably still open. When a job finishes Oban tries to unlock it, but if it gets a connection from the pool that is different than the connection that locked it the unlock can fail. For typical usage this shouldn't be a problem, but with multiple active iex sessions it could happen.

Thanks for the info. I plan on adding a blanket `pg_advisory_unlock_all` call from producers when there aren't any active jobs, which may help with this issue.

**Comment by axelson** [comment]
Okay, that makes sense :+1: Thanks for the help!
