### ISSUE TITLE
Frozen unique jobs are never going to be failed

### ISSUE THREAD

**Issue by marinakr** [sorentwo/oban#424]
Hi, I got an issue with unfinished oban jobs frozen in `executing` status
Settings:
```  use Oban.Worker, queue: :projects, max_attempts: 1, unique: [period: 60]```
Steps to reproduce
1) Run long-time jobs
2) Shut down application
3.1) Jobs are `executing`
```
ms_365_oban=# select id, state, scheduled_at, attempted_at from oban_jobs where state = 'executing';
  id  |   state   |        scheduled_at        |        attempted_at        
------+-----------+----------------------------+----------------------------
 3715 | executing | 2021-02-08 03:21:05.069831 | 2021-02-08 03:21:05.07876
 4411 | executing | 2021-02-08 04:41:02.680708 | 2021-02-08 04:41:02.685258
```
3) Restart application
3.1) Jobs are `executing` still 
```
ms_365_oban=# select id, state, scheduled_at, attempted_at from oban_jobs where state = 'executing';
  id  |   state   |        scheduled_at        |        attempted_at        
------+-----------+----------------------------+----------------------------
 3715 | executing | 2021-02-08 03:21:05.069831 | 2021-02-08 03:21:05.07876
 4411 | executing | 2021-02-08 04:41:02.680708 | 2021-02-08 04:41:02.685258
```
Maybe it is possible to add check like PID, called Oban, is alive?

**Comment by v0idpwn** [comment]
I think this is solved by Oban Pro's lifeline plugin: https://hexdocs.pm/oban/lifeline.html#content

**Comment by marinakr** [comment]
Thank you!
 I will check it and write update

**Comment by marinakr** [comment]
@v0idpwn this fix available only in Pro?

**Comment by sorentwo** [comment]
@marinakr the immediate fix is to manually change the state back to `available` in the db. The Lifeline plugin in Pro does that automatically, along with activity tracking for the UI.

This is a natural byproduct of apps shutting down, btw. Oban tries to pause queues and let executing jobs finish, but that doesn’t always work. With most other job processors the job would just be gone forever and you wouldn’t know.

**Comment by marinakr** [comment]
@v0idpwn my organization is using oban pro. I just added `mix hex.organization auth oban --key $OBAN_KEY`, updated deps, added plugin, but still have issue with start - this module is not exists.
Can you give me an advise, what did I forget and how make `Oban.Pro.Plugins.Lifeline` module appear?

**Comment by giddie** [comment]
I'm concerned that this seems like a really important correctness check to be missing from Oban proper. Resque / Sidekiq handle this automatically out of the box. For an app that is re-deployed multiple times a day, the risk is quite high that jobs will get stuck in "Executing" and never retried, which is not really expected behaviour. I've seen this happen too.

**Comment by sorentwo** [comment]
> Resque / Sidekiq handle this automatically out of the box.

Sidekiq definitely doesn’t handle this out of the box. If it pops a job and the app shuts down the job is lost forever. Look at the “Reliability” section of the Pro docs for detail: https://sidekiq.org/products/pro.html

As a Sidekiq user there isn’t anything you can do about that without upgrading to Pro.

In contrast, you’ll never lose the job in Oban, it just gets stuck temporarily. As an Oban user you can easily fix it manually, or you can upgrade and let Pro do it automatically.

**Comment by giddie** [comment]
My bad; I was sure I saw a locked_by or similar column in sidekiq that held the pid of the worker that checked out the job. The documentation certainly seems to agree that proper error handling is only implemented in the pro version :+1:
